const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const contractRouter = require('./contractRouter')
const allowancesRouter = require('./allowancesRouter')
const absenteeismRouter = require('./absenteeismRouter')
const threeMonthDataRouter = require('./threeMonthDataRouter')
const typesOfSickLeaveRouter = require('./typesOfSickLeaveRouter')
const sickLeaveRequestsRouter = require('./sickLeaveRequestsRouter')
const typesOfVacationsRouter = require('./typesOfVacationsRouter')
const vacationRequestsRouter = require('./vacationRequestRouter')
const missingWorkersRouter = require('./missingWorkersRouter')
const numberOfSpentDaysRouter = require('./numberOfSpentDaysRouter')

router.use('/user', userRouter)
router.use('/contract', contractRouter)
router.use('/allowances', allowancesRouter)
router.use('/absenteeism', absenteeismRouter)
router.use('/threeMonthData', threeMonthDataRouter)
router.use('/typesOfSickLeave', typesOfSickLeaveRouter)
router.use('/sickLeaveRequests', sickLeaveRequestsRouter)
router.use('/typesOfVacations', typesOfVacationsRouter)
router.use('/vacationRequests', vacationRequestsRouter)
router.use('/missingWorkers', missingWorkersRouter)
router.use('/numberOfSpentDays', numberOfSpentDaysRouter)

module.exports = router